# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ac7ded2b-3cc0-4994-9d52-6ffd8bb3971c";
    fsType = "btrfs";
    options = [
      "subvol=@nixos/@"
      "noatime"
      "compress-force=zstd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/ac7ded2b-3cc0-4994-9d52-6ffd8bb3971c";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "noatime"
      "compress-force=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/ac7ded2b-3cc0-4994-9d52-6ffd8bb3971c";
    fsType = "btrfs";
    options = [
      "subvol=@nixos/@nix"
      "noatime"
      "compress-force=zstd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/141F-CADA";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/3c654289-c5b8-4ddc-b081-5216223b885d"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
