name: nix ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1

      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            auto-optimise-store = true

      - name: Setup Cachix
        uses: cachix/cachix-action@v13
        with:
          name: uku3lig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix run --inputs-from . --override-input nixpkgs nixpkgs github:Mic92/nix-fast-build -- --no-nom --skip-cached --option accept-flake-config true --flake '.#hydraJobs'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9

      - name: connect to tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gha

      - name: copy known_hosts
        run: |
          set -eux

          [ ! -d ~/.ssh ] && mkdir -p ~/.ssh
          cp .known_hosts ~/.ssh/known_hosts

      - name: deploy
        run: nix run --inputs-from . 'nixpkgs#deploy-rs' -- -s
